import { getDayOfYear } from "date-fns";

export type QuoteType = "saint" | "bible";

export interface DailyQuote {
  text: string;
  source: string;
  type: QuoteType;
}

const QUOTES: DailyQuote[] = [
  { text: "O Senhor é o meu pastor; nada me faltará.", source: "Sl 23,1", type: "bible" },
  { text: "Deus amou o mundo de tal maneira que deu o seu Filho unigênito.", source: "Jo 3,16", type: "bible" },
  { text: "Tudo posso naquele que me fortalece.", source: "Fl 4,13", type: "bible" },
  { text: "Buscai primeiro o Reino de Deus e a sua justiça.", source: "Mt 6,33", type: "bible" },
  { text: "Vinde a mim, vós todos que estais cansados e oprimidos, e eu vos aliviarei.", source: "Mt 11,28", type: "bible" },
  { text: "Onde estiver o teu tesouro, aí estará também o teu coração.", source: "Mt 6,21", type: "bible" },
  { text: "Amai-vos uns aos outros como eu vos amei.", source: "Jo 15,12", type: "bible" },
  { text: "Não temais, porque eu estou convosco.", source: "Is 41,10", type: "bible" },
  { text: "O Senhor é a minha luz e a minha salvação; de quem terei medo?", source: "Sl 27,1", type: "bible" },
  { text: "Lançai sobre Ele toda a vossa ansiedade, porque Ele cuida de vós.", source: "1 Pe 5,7", type: "bible" },
  { text: "Orai sem cessar.", source: "1 Ts 5,17", type: "bible" },
  { text: "A paz vos deixo, a minha paz vos dou.", source: "Jo 14,27", type: "bible" },
  { text: "Eis que estou convosco todos os dias.", source: "Mt 28,20", type: "bible" },
  { text: "O Senhor está perto de todos os que o invocam.", source: "Sl 145,18", type: "bible" },
  { text: "Sede fortes na fé.", source: "1 Co 16,13", type: "bible" },
  { text: "O Senhor te abençoe e te guarde.", source: "Nm 6,24", type: "bible" },
  { text: "Alegrai-vos sempre no Senhor.", source: "Fl 4,4", type: "bible" },
  { text: "A palavra de Deus é viva e eficaz.", source: "Hb 4,12", type: "bible" },
  { text: "O amor é paciente, o amor é bondoso.", source: "1 Co 13,4", type: "bible" },
  { text: "Confiai no Senhor de todo o coração.", source: "Pv 3,5", type: "bible" },
  { text: "Sede santos, porque eu sou santo.", source: "Lv 19,2", type: "bible" },
  { text: "Onde dois ou três estiverem reunidos em meu nome, aí estou eu.", source: "Mt 18,20", type: "bible" },
  { text: "A graça do Senhor Jesus Cristo seja convosco.", source: "Fl 4,23", type: "bible" },
  { text: "O Senhor é bom, sua misericórdia dura para sempre.", source: "Sl 100,5", type: "bible" },
  { text: "Pregai o Evangelho a toda criatura.", source: "Mc 16,15", type: "bible" },
  { text: "Sede misericordiosos, como também vosso Pai é misericordioso.", source: "Lc 6,36", type: "bible" },
  { text: "O Senhor é fiel em todas as suas palavras.", source: "Sl 145,13", type: "bible" },
  { text: "Não vos conformeis com este mundo, mas transformai-vos.", source: "Rm 12,2", type: "bible" },
  { text: "O Senhor é a minha rocha, a minha fortaleza.", source: "Sl 18,2", type: "bible" },
  { text: "Perseverai na oração, vigilantes com ações de graças.", source: "Cl 4,2", type: "bible" },
  { text: "Onde há amor e caridade, aí está Deus.", source: "Santo Agostinho", type: "saint" },
  { text: "Rezai, esperai e não vos preocupeis.", source: "Padre Pio", type: "saint" },
  { text: "A alegria é a infalível sinal da presença de Deus.", source: "Pierre Teilhard de Chardin", type: "saint" },
  { text: "Nada te perturbe, nada te espante. Tudo passa. Deus não muda.", source: "Santa Teresa d'Ávila", type: "saint" },
  { text: "Onde não puderes amar, pelo menos não causes mal.", source: "São Francisco de Assis", type: "saint" },
  { text: "A oração é o diálogo da alma com Deus.", source: "Santa Teresa d'Ávila", type: "saint" },
  { text: "Confie plenamente em Jesus e não tema.", source: "Santa Faustina Kowalska", type: "saint" },
  { text: "Façamos tudo por amor.", source: "São Vicente de Paulo", type: "saint" },
  { text: "A paciência alcança tudo.", source: "Santa Teresa d'Ávila", type: "saint" },
  { text: "Quem possui Deus nada mais lhe falta.", source: "São Tomás de Aquino", type: "saint" },
  { text: "Deus escreve certo por linhas tortas.", source: "São José de Cupertino", type: "saint" },
  { text: "A cruz é a escola do amor.", source: "São Maximiliano Kolbe", type: "saint" },
  { text: "Sede bons, não façais mal a ninguém.", source: "São João Bosco", type: "saint" },
  { text: "A humildade é a verdade.", source: "Santa Teresa d'Ávila", type: "saint" },
  { text: "Deus não nos pede o impossível, mas nos dá a graça.", source: "Santo Agostinho", type: "saint" },
  { text: "A caridade é o amor de Deus e do próximo.", source: "São Tomás de Aquino", type: "saint" },
  { text: "Onde há humildade, há sabedoria.", source: "São Bento", type: "saint" },
  { text: "A oração é a respiração da alma.", source: "São João Crisóstomo", type: "saint" },
  { text: "Deus chama quem Ele quer, não quem está pronto.", source: "São Padre Pio", type: "saint" },
  { text: "Ame a Deus e faça o que quiser.", source: "Santo Agostinho", type: "saint" },
  { text: "A santidade não consiste em fazer coisas extraordinárias, mas em fazer o ordinário extraordinariamente bem.", source: "São José Maria Escrivá", type: "saint" },
  { text: "Confie em Deus e Ele cuidará de tudo.", source: "Santa Teresinha do Menino Jesus", type: "saint" },
  { text: "A cruz é o caminho para a glória.", source: "São Paulo", type: "saint" },
  { text: "Deus nunca abandona quem confia Nele.", source: "São Padre Pio", type: "saint" },
  { text: "A paz começa com um sorriso.", source: "Santa Teresa de Calcutá", type: "saint" },
  { text: "O silêncio é a primeira linguagem de Deus.", source: "São João da Cruz", type: "saint" },
  { text: "Quem tem Deus, tem tudo.", source: "Santa Teresinha do Menino Jesus", type: "saint" },
  { text: "A oração é o alimento da alma.", source: "São Francisco de Assis", type: "saint" },
  { text: "Deus usa nossas fraquezas para mostrar Sua força.", source: "São Paulo", type: "saint" },
  { text: "A esperança é a certeza de que Deus cumprirá Suas promessas.", source: "Santo Agostinho", type: "saint" },
  { text: "Servir é reinar.", source: "São Vicente de Paulo", type: "saint" },
  { text: "A fé move montanhas.", source: "São Francisco de Assis", type: "saint" },
  { text: "Deus é mais bonito que o mais belo dos dias.", source: "São João da Cruz", type: "saint" },
  { text: "A misericórdia de Deus é infinita.", source: "Santa Faustina Kowalska", type: "saint" },
  { text: "O amor de Deus nunca falha.", source: "São Paulo", type: "saint" },
  { text: "A cruz é o trono do amor.", source: "São Maximiliano Kolbe", type: "saint" },
  { text: "Deus nos ama como somos, mas não quer que fiquemos como estamos.", source: "São Agostinho", type: "saint" },
  { text: "A oração é conversar com Deus como quem fala com um amigo.", source: "Santa Teresa d'Ávila", type: "saint" },
  { text: "Confie no Senhor de todo o coração.", source: "São Francisco de Sales", type: "saint" },
  { text: "A alegria do Senhor é a nossa força.", source: "São Francisco de Assis", type: "saint" },
  { text: "Deus é fiel às Suas promessas.", source: "São Paulo", type: "saint" },
  { text: "A humildade é a mãe de todas as virtudes.", source: "São Tomás de Aquino", type: "saint" },
  { text: "O amor de Cristo impulsiona-nos.", source: "São Paulo", type: "saint" },
  { text: "Deus nos chama à santidade no dia a dia.", source: "São José Maria Escrivá", type: "saint" },
  { text: "A paz interior nasce da confiança em Deus.", source: "São Francisco de Sales", type: "saint" },
  { text: "O Senhor é meu refúgio e fortaleza.", source: "Sl 46,1", type: "bible" },
  { text: "Bendize, ó minha alma, ao Senhor.", source: "Sl 103,1", type: "bible" },
  { text: "O Senhor é compassivo e misericordioso.", source: "Sl 103,8", type: "bible" },
  { text: "Entregai-vos a Deus, confiai Nele.", source: "Sl 37,5", type: "bible" },
  { text: "O Senhor é a minha força e o meu cântico.", source: "Ex 15,2", type: "bible" },
  { text: "Bem-aventurados os pacificadores.", source: "Mt 5,9", type: "bible" },
  { text: "Bem-aventurados os pobres de espírito.", source: "Mt 5,3", type: "bible" },
  { text: "Vós sois a luz do mundo.", source: "Mt 5,14", type: "bible" },
  { text: "Vós sois o sal da terra.", source: "Mt 5,13", type: "bible" },
  { text: "Perdoai setenta vezes sete.", source: "Mt 18,22", type: "bible" },
  { text: "O maior entre vós seja vosso servidor.", source: "Mt 23,11", type: "bible" },
  { text: "Ide e fazei discípulos de todas as nações.", source: "Mt 28,19", type: "bible" },
  { text: "O Espírito Santo vos ensinará.", source: "Lc 12,12", type: "bible" },
  { text: "A vossa fé salvou-vos.", source: "Lc 7,50", type: "bible" },
  { text: "Ninguém tem maior amor do que dar a vida pelos amigos.", source: "Jo 15,13", type: "bible" },
  { text: "Eu sou o caminho, a verdade e a vida.", source: "Jo 14,6", type: "bible" },
  { text: "Eu sou a ressurreição e a vida.", source: "Jo 11,25", type: "bible" },
  { text: "Eu sou a videira, vós sois os ramos.", source: "Jo 15,5", type: "bible" },
  { text: "Recebei o Espírito Santo.", source: "Jo 20,22", type: "bible" },
  { text: "A caridade nunca acaba.", source: "1 Co 13,8", type: "bible" },
  { text: "O amor de Deus foi derramado em nossos corações.", source: "Rm 5,5", type: "bible" },
  { text: "Nada nos separará do amor de Deus.", source: "Rm 8,39", type: "bible" },
  { text: "Presenteai-vos uns aos outros.", source: "Rm 12,10", type: "bible" },
  { text: "Regozijai-vos na esperança.", source: "Rm 12,12", type: "bible" },
  { text: "Sede imitadores de Deus, como filhos amados.", source: "Ef 5,1", type: "bible" },
  { text: "Revesti-vos de compaixão, bondade e humildade.", source: "Cl 3,12", type: "bible" },
  { text: "Orai por todos os homens.", source: "1 Tm 2,1", type: "bible" },
  { text: "A fé sem obras é morta.", source: "Tg 2,26", type: "bible" },
  { text: "Deus resiste aos soberbos, mas dá graça aos humildes.", source: "Tg 4,6", type: "bible" },
  { text: "O Senhor não retarda a Sua promessa.", source: "2 Pe 3,9", type: "bible" },
  { text: "Eis que faço novas todas as coisas.", source: "Ap 21,5", type: "bible" },
  { text: "Vinde, benditos de meu Pai.", source: "Mt 25,34", type: "bible" },
  { text: "O Senhor é rei, revestiu-se de majestade.", source: "Sl 93,1", type: "bible" },
  { text: "Cantai ao Senhor um cântico novo.", source: "Sl 96,1", type: "bible" },
  { text: "Exultai no Senhor, ó justos.", source: "Sl 32,11", type: "bible" },
  { text: "O Senhor é a minha herança.", source: "Sl 16,5", type: "bible" },
  { text: "Espera no Senhor, sê forte.", source: "Sl 27,14", type: "bible" },
  { text: "O Senhor é bom para com os que esperam Nele.", source: "Lm 3,25", type: "bible" },
  { text: "Deus é o nosso refúgio e fortaleza.", source: "Sl 46,1", type: "bible" },
  { text: "Bendito seja o nome do Senhor.", source: "Jó 1,21", type: "bible" },
  { text: "O Senhor deu, o Senhor tomou.", source: "Jó 1,21", type: "bible" },
  { text: "Conhecei e vede que o Senhor é bom.", source: "Sl 34,8", type: "bible" },
  { text: "Glorificai ao Senhor, porque Ele é bom.", source: "Sl 136,1", type: "bible" },
  { text: "O Senhor é a minha porção.", source: "Sl 119,57", type: "bible" },
  { text: "Lâmpada para os meus pés é a tua palavra.", source: "Sl 119,105", type: "bible" },
  { text: "Ensinai-nos a contar os nossos dias.", source: "Sl 90,12", type: "bible" },
  { text: "O Senhor é o meu escudo.", source: "Sl 3,4", type: "bible" },
  { text: "Deus é o nosso auxílio nas tribulações.", source: "Sl 46,1", type: "bible" },
  { text: "O Senhor sustenta os que tropeçam.", source: "Sl 145,14", type: "bible" },
  { text: "O Senhor cura os corações feridos.", source: "Sl 147,3", type: "bible" },
  { text: "Bendize, ó minha alma, ao Senhor, e não te esqueças de nenhum de seus benefícios.", source: "Sl 103,2", type: "bible" },
  { text: "Como a corça suspira pelas águas, assim a minha alma suspira por ti, ó Deus.", source: "Sl 42,1", type: "bible" },
  { text: "O Senhor é a minha rocha e o meu Redentor.", source: "Sl 19,14", type: "bible" },
  { text: "Deus é amor.", source: "1 Jo 4,8", type: "bible" },
  { text: "Nós o amamos porque Ele nos amou primeiro.", source: "1 Jo 4,19", type: "bible" },
  { text: "O amor lança fora o medo.", source: "1 Jo 4,18", type: "bible" },
  { text: "Permanecei no amor de Deus.", source: "Jud 1,21", type: "bible" },
  { text: "A graça e a paz vos sejam multiplicadas.", source: "1 Pe 1,2", type: "bible" },
  { text: "Sede firmes na fé.", source: "1 Pe 5,9", type: "bible" },
  { text: "O Senhor é fiel; Ele vos fortalecerá.", source: "2 Ts 3,3", type: "bible" },
  { text: "O Senhor é justo em todos os seus caminhos.", source: "Sl 145,17", type: "bible" },
  { text: "O Senhor é misericordioso e clemente.", source: "Sl 103,8", type: "bible" },
  { text: "Deus é a minha salvação; confiarei e não temerei.", source: "Is 12,2", type: "bible" },
  { text: "Os que esperam no Senhor renovarão as suas forças.", source: "Is 40,31", type: "bible" },
  { text: "Eu sei os planos que tenho para vós, diz o Senhor.", source: "Jr 29,11", type: "bible" },
  { text: "Invocai-me no dia da angústia; eu vos livrarei.", source: "Sl 50,15", type: "bible" },
  { text: "O Senhor é o meu auxílio.", source: "Hb 13,6", type: "bible" },
  { text: "Aproximai-vos de Deus, e Ele se aproximará de vós.", source: "Tg 4,8", type: "bible" },
  { text: "Buscai a paz e segui-a.", source: "1 Pe 3,11", type: "bible" },
  { text: "O Senhor é a minha justiça.", source: "Jr 23,6", type: "bible" },
  { text: "Deus é o nosso Pai.", source: "Mt 6,9", type: "bible" },
  { text: "Santificado seja o vosso nome.", source: "Mt 6,9", type: "bible" },
  { text: "Venha a nós o vosso Reino.", source: "Mt 6,10", type: "bible" },
  { text: "O Pai Nosso que estais nos céus.", source: "Mt 6,9", type: "bible" },
  { text: "Perdoai-nos as nossas ofensas.", source: "Mt 6,12", type: "bible" },
  { text: "Não nos deixeis cair em tentação.", source: "Mt 6,13", type: "bible" },
  { text: "Livrai-nos do mal.", source: "Mt 6,13", type: "bible" },
  { text: "Ave Maria, cheia de graça.", source: "Lc 1,28", type: "bible" },
  { text: "Magnificat anima mea Dominum.", source: "Lc 1,46", type: "bible" },
  { text: "A minha alma glorifica ao Senhor.", source: "Lc 1,46", type: "bible" },
  { text: "Eis aqui a serva do Senhor.", source: "Lc 1,38", type: "bible" },
  { text: "Faça-se em mim segundo a tua palavra.", source: "Lc 1,38", type: "bible" },
  { text: "Gloria in excelsis Deo.", source: "Lc 2,14", type: "bible" },
  { text: "Glória a Deus nas alturas.", source: "Lc 2,14", type: "bible" },
  { text: "Paz na terra aos homens de boa vontade.", source: "Lc 2,14", type: "bible" },
  { text: "Este é o meu Filho amado.", source: "Mt 3,17", type: "bible" },
  { text: "Convertei-vos, porque o Reino dos céus está próximo.", source: "Mt 4,17", type: "bible" },
  { text: "Segui-me.", source: "Mt 4,19", type: "bible" },
  { text: "Eu sou o pão da vida.", source: "Jo 6,35", type: "bible" },
  { text: "Este é o meu corpo.", source: "Mt 26,26", type: "bible" },
  { text: "Fazei isto em memória de mim.", source: "Lc 22,19", type: "bible" },
  { text: "Pai, nas tuas mãos entrego o meu espírito.", source: "Lc 23,46", type: "bible" },
  { text: "Está consumado.", source: "Jo 19,30", type: "bible" },
  { text: "Porque também Cristo padeceu por nós.", source: "1 Pe 2,21", type: "bible" },
  { text: "Cristo ressuscitou dos mortos.", source: "1 Co 15,20", type: "bible" },
  { text: "Onde, ó morte, está a tua vitória?", source: "1 Co 15,55", type: "bible" },
  { text: "Aleluia! O Senhor ressuscitou.", source: "Tradição litúrgica", type: "bible" },
  { text: "O Espírito Santo virá sobre vós.", source: "At 1,8", type: "bible" },
  { text: "Sereis minhas testemunhas.", source: "At 1,8", type: "bible" },
  { text: "Recebestes o Espírito Santo.", source: "At 2,4", type: "bible" },
  { text: "Arrependei-vos e crede no Evangelho.", source: "Mc 1,15", type: "bible" },
  { text: "A palavra de Deus não está presa.", source: "2 Tm 2,9", type: "bible" },
  { text: "Combati o bom combate.", source: "2 Tm 4,7", type: "bible" },
  { text: "Guardei a fé.", source: "2 Tm 4,7", type: "bible" },
  { text: "Coragem! Eu venci o mundo.", source: "Jo 16,33", type: "bible" },
  { text: "A paz de Cristo domine em vossos corações.", source: "Cl 3,15", type: "bible" },
  { text: "Fazei tudo com amor.", source: "1 Co 16,14", type: "bible" },
  { text: "Deus é fiel.", source: "1 Co 1,9", type: "bible" },
  { text: "O Senhor é o meu pastor, nada me faltará.", source: "Sl 23,1", type: "bible" },
  { text: "Ainda que eu ande pelo vale da sombra da morte, não temerei mal algum.", source: "Sl 23,4", type: "bible" },
  { text: "Preparaste uma mesa diante de mim.", source: "Sl 23,5", type: "bible" },
  { text: "A bondade e a misericórdia me seguirão todos os dias.", source: "Sl 23,6", type: "bible" },
  { text: "Habitarei na casa do Senhor por longos dias.", source: "Sl 23,6", type: "bible" },
  { text: "O Senhor é o meu rochedo.", source: "Sl 18,2", type: "bible" },
  { text: "O Senhor é a minha libertação.", source: "Sl 18,2", type: "bible" },
  { text: "Invocarei o nome do Senhor.", source: "Sl 18,3", type: "bible" },
  { text: "Dai graças ao Senhor, porque Ele é bom.", source: "Sl 118,1", type: "bible" },
  { text: "O Senhor ouviu a minha súplica.", source: "Sl 116,1", type: "bible" },
  { text: "Guardarei o teu nome no meu coração.", source: "Sl 63,7", type: "bible" },
  { text: "A tua misericórdia vale mais que a vida.", source: "Sl 63,4", type: "bible" },
  { text: "A minha alma tem sede de Deus.", source: "Sl 63,2", type: "bible" },
  { text: "Bendito seja Deus, que não rejeitou a minha oração.", source: "Sl 66,20", type: "bible" },
  { text: "Clamai a Deus com alegria.", source: "Sl 66,1", type: "bible" },
  { text: "O Senhor é rei eternamente.", source: "Sl 29,10", type: "bible" },
  { text: "O Senhor dá força ao seu povo.", source: "Sl 29,11", type: "bible" },
  { text: "O Senhor abençoe o seu povo com a paz.", source: "Sl 29,11", type: "bible" },
  { text: "Espera no Senhor e guarda o seu caminho.", source: "Sl 37,34", type: "bible" },
  { text: "Delicia-te no Senhor, e Ele concederá os desejos do teu coração.", source: "Sl 37,4", type: "bible" },
  { text: "O Senhor conhece os dias dos íntegros.", source: "Sl 37,18", type: "bible" },
  { text: "O Senhor é o meu auxílio, não temerei.", source: "Sl 118,6", type: "bible" },
  { text: "Melhor é um dia nos teus átrios.", source: "Sl 84,11", type: "bible" },
  { text: "Como a corça anseia por correntes de águas.", source: "Sl 42,2", type: "bible" },
  { text: "Espera em Deus, pois ainda o louvarei.", source: "Sl 42,12", type: "bible" },
  { text: "Enviai a vossa luz e a vossa verdade.", source: "Sl 43,3", type: "bible" },
  { text: "Deus é o nosso refúgio.", source: "Sl 46,1", type: "bible" },
  { text: "Estai quietos e sabei que eu sou Deus.", source: "Sl 46,10", type: "bible" },
  { text: "O Senhor dos exércitos está conosco.", source: "Sl 46,8", type: "bible" },
  { text: "Cantai salmos ao Senhor.", source: "Sl 98,1", type: "bible" },
  { text: "Aclamai ao Senhor, terra inteira.", source: "Sl 98,4", type: "bible" },
  { text: "Entrai pelas portas do Senhor com louvor.", source: "Sl 100,4", type: "bible" },
  { text: "Rendei graças e bendizei o seu nome.", source: "Sl 100,4", type: "bible" },
  { text: "Bendize, ó minha alma, ao Senhor.", source: "Sl 104,1", type: "bible" },
  { text: "O Senhor veste-se de luz como de um manto.", source: "Sl 104,2", type: "bible" },
  { text: "Enviai a vossa luz e a vossa verdade.", source: "Sl 43,3", type: "bible" },
  { text: "O Senhor é a minha luz.", source: "Sl 27,1", type: "bible" },
  { text: "Uma coisa peço ao Senhor: habitar no templo do Senhor.", source: "Sl 27,4", type: "bible" },
  { text: "O Senhor é a fortaleza da minha vida.", source: "Sl 27,1", type: "bible" },
  { text: "Se Deus é por nós, quem será contra nós?", source: "Rm 8,31", type: "bible" },
  { text: "Regozijai-vos sempre no Senhor.", source: "Fl 4,4", type: "bible" },
  { text: "A paz de Deus guardará os vossos corações.", source: "Fl 4,7", type: "bible" },
  { text: "O Senhor está perto.", source: "Fl 4,5", type: "bible" },
  { text: "Sede alegres na esperança.", source: "Rm 12,12", type: "bible" },
  { text: "Perseverai na oração.", source: "Rm 12,12", type: "bible" },
  { text: "Sede hospitaleiros uns para com os outros.", source: "Rm 12,13", type: "bible" },
  { text: "Abençoai os que vos perseguem.", source: "Rm 12,14", type: "bible" },
  { text: "Vivei em paz com todos.", source: "Rm 12,18", type: "bible" },
  { text: "Não vos vingueis.", source: "Rm 12,19", type: "bible" },
  { text: "Se o teu inimigo tiver fome, dá-lhe de comer.", source: "Rm 12,20", type: "bible" },
  { text: "Não sejas vencido pelo mal.", source: "Rm 12,21", type: "bible" },
  { text: "Vence o mal com o bem.", source: "Rm 12,21", type: "bible" },
  { text: "Honrai a vossos pais.", source: "Ef 6,2", type: "bible" },
  { text: "Vestí-vos de armadura de Deus.", source: "Ef 6,11", type: "bible" },
  { text: "Orai em todo tempo no Espírito.", source: "Ef 6,18", type: "bible" },
  { text: "Vigiai com toda perseverança.", source: "Ef 6,18", type: "bible" },
  { text: "Tudo o que fizerdes, fazei-o de coração.", source: "Cl 3,23", type: "bible" },
  { text: "Como ao Senhor, e não aos homens.", source: "Cl 3,23", type: "bible" },
  { text: "A palavra de Cristo habite em vós.", source: "Cl 3,16", type: "bible" },
  { text: "Cantai salmos, hinos e cânticos espirituais.", source: "Cl 3,16", type: "bible" },
  { text: "Dai graças a Deus por tudo.", source: "1 Ts 5,18", type: "bible" },
  { text: "Examinai tudo e retende o bem.", source: "1 Ts 5,21", type: "bible" },
  { text: "O Senhor vos santifique em tudo.", source: "1 Ts 5,23", type: "bible" },
  { text: "A graça do Senhor Jesus seja convosco.", source: "1 Ts 5,28", type: "bible" },
  { text: "O Senhor é fiel; Ele vos guardará.", source: "2 Ts 3,3", type: "bible" },
  { text: "O Senhor vos dê paz sempre.", source: "2 Ts 3,16", type: "bible" },
  { text: "Combati o bom combate, terminei a carreira.", source: "2 Tm 4,7", type: "bible" },
  { text: "Guardei a fé. Desde agora me está reservada a coroa.", source: "2 Tm 4,8", type: "bible" },
  { text: "O Senhor me livrará de toda obra má.", source: "2 Tm 4,18", type: "bible" },
  { text: "A graça do Senhor Jesus seja convosco.", source: "2 Tm 4,22", type: "bible" },
  { text: "Deus não nos deu espírito de timidez.", source: "2 Tm 1,7", type: "bible" },
  { text: "Deus nos deu espírito de fortaleza, amor e sobriedade.", source: "2 Tm 1,7", type: "bible" },
  { text: "Sede fortes na graça de Cristo.", source: "2 Tm 2,1", type: "bible" },
  { text: "O Senhor conhece os que lhe pertencem.", source: "2 Tm 2,19", type: "bible" },
  { text: "A Escritura é inspirada por Deus.", source: "2 Tm 3,16", type: "bible" },
  { text: "A Escritura é útil para ensinar e corrigir.", source: "2 Tm 3,16", type: "bible" },
  { text: "Prega a palavra, insta a tempo e fora de tempo.", source: "2 Tm 4,2", type: "bible" },
  { text: "Sede sóbrios e vigilantes.", source: "1 Pe 5,8", type: "bible" },
  { text: "Resistí ao diabo, e ele fugirá de vós.", source: "Tg 4,7", type: "bible" },
  { text: "Purificai as vossas mãos.", source: "Tg 4,8", type: "bible" },
  { text: "Humilhai-vos diante do Senhor.", source: "Tg 4,10", type: "bible" },
  { text: "Não faleis mal uns dos outros.", source: "Tg 4,11", type: "bible" },
  { text: "Se alguém entre vós está triste, ore.", source: "Tg 5,13", type: "bible" },
  { text: "A oração do justo pode muito.", source: "Tg 5,16", type: "bible" },
  { text: "Confessai as vossas culpas uns aos outros.", source: "Tg 5,16", type: "bible" },
  { text: "Orai uns pelos outros.", source: "Tg 5,16", type: "bible" },
  { text: "Deus é luz, e nele não há trevas.", source: "1 Jo 1,5", type: "bible" },
  { text: "Se andarmos na luz, temos comunhão uns com os outros.", source: "1 Jo 1,7", type: "bible" },
  { text: "Confessai os vossos pecados.", source: "1 Jo 1,9", type: "bible" },
  { text: "Deus é fiel e justo para nos perdoar.", source: "1 Jo 1,9", type: "bible" },
  { text: "Amai-vos uns aos outros.", source: "1 Jo 4,7", type: "bible" },
  { text: "Quem ama, nasceu de Deus e conhece a Deus.", source: "1 Jo 4,7", type: "bible" },
  { text: "Deus permanece em nós.", source: "1 Jo 4,12", type: "bible" },
  { text: "Deus é amor; quem permanece no amor permanece em Deus.", source: "1 Jo 4,16", type: "bible" },
  { text: "Amai-vos uns aos outros, como Cristo nos amou.", source: "Jo 13,34", type: "bible" },
  { text: "Servi uns aos outros com amor.", source: "Gl 5,13", type: "bible" },
  { text: "O fruto do Espírito é amor, alegria, paz.", source: "Gl 5,22", type: "bible" },
  { text: "Paciência, benignidade, bondade, fidelidade.", source: "Gl 5,22", type: "bible" },
  { text: "Mansidão, domínio próprio.", source: "Gl 5,23", type: "bible" },
  { text: "Vivei pelo Espírito.", source: "Gl 5,25", type: "bible" },
  { text: "Carregai os fardos uns dos outros.", source: "Gl 6,2", type: "bible" },
  { text: "Cumpri a lei de Cristo.", source: "Gl 6,2", type: "bible" },
  { text: "Não nos cansemos de fazer o bem.", source: "Gl 6,9", type: "bible" },
  { text: "Façamos o bem a todos.", source: "Gl 6,10", type: "bible" },
  { text: "Gloriai-vos na cruz de Cristo.", source: "Gl 6,14", type: "bible" },
  { text: "Cristo vive em mim.", source: "Gl 2,20", type: "bible" },
  { text: "Vivo pela fé no Filho de Deus.", source: "Gl 2,20", type: "bible" },
  { text: "Crê no Senhor Jesus e serás salvo.", source: "At 16,31", type: "bible" },
  { text: "Há salvação em nenhum outro.", source: "At 4,12", type: "bible" },
  { text: "Não há outro nome dado aos homens.", source: "At 4,12", type: "bible" },
  { text: "Deus fez de um só sangue toda a humanidade.", source: "At 17,26", type: "bible" },
  { text: "Nele vivemos, movemo-nos e existimos.", source: "At 17,28", type: "bible" },
  { text: "Deus não está longe de cada um de nós.", source: "At 17,27", type: "bible" },
  { text: "Arrependei-vos.", source: "At 2,38", type: "bible" },
  { text: "Sede batizados.", source: "At 2,38", type: "bible" },
  { text: "Recebereis o dom do Espírito Santo.", source: "At 2,38", type: "bible" },
  { text: "Salvai-vos desta geração perversa.", source: "At 2,40", type: "bible" },
  { text: "Deus ressuscitou a Jesus.", source: "At 2,32", type: "bible" },
  { text: "Deus o fez Senhor e Cristo.", source: "At 2,36", type: "bible" },
  { text: "Há remissão dos pecados em Seu nome.", source: "At 10,43", type: "bible" },
  { text: "Deus não faz acepção de pessoas.", source: "At 10,34", type: "bible" },
  { text: "Deus aceita todo aquele que O teme.", source: "At 10,35", type: "bible" },
  { text: "Deus enviou a pregação da paz.", source: "At 10,36", type: "bible" },
  { text: "Deus ungiu Jesus com o Espírito Santo.", source: "At 10,38", type: "bible" },
  { text: "Jesus andou fazendo o bem.", source: "At 10,38", type: "bible" },
  { text: "Deus estava com Ele.", source: "At 10,38", type: "bible" },
  { text: "Deus o ressuscitou ao terceiro dia.", source: "At 10,40", type: "bible" },
  { text: "Deus o constituiu juiz dos vivos e dos mortos.", source: "At 10,42", type: "bible" },
  { text: "A todos os profetas dão testemunho de Jesus.", source: "At 10,43", type: "bible" },
  { text: "Quem crê nele recebe remissão dos pecados.", source: "At 10,43", type: "bible" },
  { text: "O Espírito Santo caiu sobre todos.", source: "At 10,44", type: "bible" },
  { text: "Deus deu a eles o mesmo dom.", source: "At 11,17", type: "bible" },
  { text: "Deus deu aos gentios o arrependimento para a vida.", source: "At 11,18", type: "bible" },
  { text: "Deus abriu a porta da fé aos gentios.", source: "At 14,27", type: "bible" },
  { text: "Deus fez maravilhas entre os gentios.", source: "At 15,12", type: "bible" },
  { text: "Deus conhece o coração desde a eternidade.", source: "At 15,18", type: "bible" },
  { text: "Deus purificou os corações pela fé.", source: "At 15,9", type: "bible" },
  { text: "Deus visitou os gentios para tomar deles um povo.", source: "At 15,14", type: "bible" },
  { text: "Deus fez conhecer o caminho da salvação.", source: "At 16,17", type: "bible" },
  { text: "Crê no Senhor Jesus.", source: "At 16,31", type: "bible" },
  { text: "Tu e tua casa sereis salvos.", source: "At 16,31", type: "bible" },
  { text: "Deus abriu o coração para ouvir a palavra.", source: "At 16,14", type: "bible" },
  { text: "Deus fez maravilhas e sinais.", source: "At 15,12", type: "bible" },
  { text: "Deus deu testemunho da palavra da graça.", source: "At 14,3", type: "bible" },
  { text: "Deus fez maravilhas por suas mãos.", source: "At 19,11", type: "bible" },
  { text: "Deus fez crescer a palavra.", source: "At 19,20", type: "bible" },
  { text: "Deus fez prevalecer o caminho do Senhor.", source: "At 19,20", type: "bible" },
  { text: "Deus fez maravilhas por Paulo.", source: "At 19,11", type: "bible" },
  { text: "Deus fez conhecer o caminho da salvação.", source: "At 16,17", type: "bible" },
  { text: "Deus fez maravilhas entre nós.", source: "At 2,43", type: "bible" },
  { text: "Deus fez crescer a igreja.", source: "At 2,47", type: "bible" },
  { text: "Deus acrescentava diariamente os salvos.", source: "At 2,47", type: "bible" },
  { text: "Deus fez maravilhas e sinais por Jesus.", source: "At 2,22", type: "bible" },
  { text: "Deus o entregou conforme o determinado conselho.", source: "At 2,23", type: "bible" },
  { text: "Deus o ressuscitou, soltando as angústias da morte.", source: "At 2,24", type: "bible" },
  { text: "Deus o ressuscitou dos mortos.", source: "At 3,15", type: "bible" },
  { text: "Deus glorificou o seu Filho Jesus.", source: "At 3,13", type: "bible" },
  { text: "Deus cumpriu o que anunciou pelos profetas.", source: "At 3,18", type: "bible" },
  { text: "Deus enviou Jesus para abençoar.", source: "At 3,26", type: "bible" },
  { text: "Deus o enviou primeiro a vós.", source: "At 3,26", type: "bible" },
  { text: "Deus o enviou para vos converter.", source: "At 3,26", type: "bible" },
  { text: "Deus o enviou para afastar-vos das maldades.", source: "At 3,26", type: "bible" },
  { text: "Deus fez maravilhas e sinais.", source: "At 4,30", type: "bible" },
  { text: "Deus estendeu a mão para curar.", source: "At 4,30", type: "bible" },
  { text: "Deus fez maravilhas em nome do teu santo Filho.", source: "At 4,30", type: "bible" },
  { text: "Deus fez prevalecer a palavra.", source: "At 6,7", type: "bible" },
  { text: "Deus fez crescer a palavra.", source: "At 12,24", type: "bible" },
  { text: "Deus fez prevalecer a palavra do Senhor.", source: "At 12,24", type: "bible" },
  { text: "Deus fez maravilhas entre os gentios.", source: "At 15,12", type: "bible" },
  { text: "Deus fez conhecer o caminho da salvação.", source: "At 16,17", type: "bible" },
  { text: "Deus abriu o coração de Lídia.", source: "At 16,14", type: "bible" },
  { text: "Deus fez maravilhas por Paulo.", source: "At 19,11", type: "bible" },
  { text: "Deus fez crescer a palavra.", source: "At 19,20", type: "bible" },
  { text: "Deus fez prevalecer o caminho do Senhor.", source: "At 19,20", type: "bible" },
  { text: "Deus fez maravilhas e sinais.", source: "At 14,3", type: "bible" },
  { text: "Deus deu testemunho da palavra da graça.", source: "At 14,3", type: "bible" },
  { text: "Deus fez maravilhas por suas mãos.", source: "At 19,11", type: "bible" },
  { text: "Deus fez crescer a palavra.", source: "At 19,20", type: "bible" },
  { text: "Deus fez prevalecer o caminho do Senhor.", source: "At 19,20", type: "bible" },
  { text: "Deus fez maravilhas por Paulo.", source: "At 19,11", type: "bible" },
  { text: "Deus fez conhecer o caminho da salvação.", source: "At 16,17", type: "bible" },
  { text: "Deus fez maravilhas entre nós.", source: "At 2,43", type: "bible" },
  { text: "Deus fez crescer a igreja.", source: "At 2,47", type: "bible" },
  { text: "Deus acrescentava diariamente os salvos.", source: "At 2,47", type: "bible" },
  { text: "Deus fez maravilhas e sinais por Jesus.", source: "At 2,22", type: "bible" },
  { text: "Deus o entregou conforme o determinado conselho.", source: "At 2,23", type: "bible" },
  { text: "Deus o ressuscitou, soltando as angústias da morte.", source: "At 2,24", type: "bible" },
  { text: "Deus o ressuscitou dos mortos.", source: "At 3,15", type: "bible" },
  { text: "Deus glorificou o seu Filho Jesus.", source: "At 3,13", type: "bible" },
  { text: "Deus cumpriu o que anunciou pelos profetas.", source: "At 3,18", type: "bible" },
  { text: "Deus enviou Jesus para abençoar.", source: "At 3,26", type: "bible" },
  { text: "Deus o enviou primeiro a vós.", source: "At 3,26", type: "bible" },
  { text: "Deus o enviou para vos converter.", source: "At 3,26", type: "bible" },
  { text: "Deus o enviou para afastar-vos das maldades.", source: "At 3,26", type: "bible" },
  { text: "Deus fez maravilhas e sinais.", source: "At 4,30", type: "bible" },
  { text: "Deus estendeu a mão para curar.", source: "At 4,30", type: "bible" },
  { text: "Deus fez maravilhas em nome do teu santo Filho.", source: "At 4,30", type: "bible" },
  { text: "Deus fez prevalecer a palavra.", source: "At 6,7", type: "bible" },
  { text: "Deus fez crescer a palavra.", source: "At 12,24", type: "bible" },
  { text: "Deus fez prevalecer a palavra do Senhor.", source: "At 12,24", type: "bible" },
];

export function getDailyQuote(date: Date = new Date()): DailyQuote {
  const dayIndex = getDayOfYear(date) - 1;
  return QUOTES[dayIndex % QUOTES.length];
}
